### ISSUE TITLE
[not needed anymore]  [howto] disable joystick mouse stering

### ISSUE THREAD

**Issue by mwozny123** [uglyDwarf/evdevshift#1]
Steps:
1. create file 
`/etc/X11/xorg.conf.d/50-joystick.conf`
2. paste content

> Section "InputClass"
>         Identifier "joystick catchall"
>         MatchIsJoystick "on"
>         MatchDevicePath "/dev/input/event*"
>         Driver "joystick"
>         Option "StartKeysEnabled" "False"       #Disable mouse
>         Option "StartMouseEnabled" "False"      #support
> EndSection

Source:
https://wiki.archlinux.org/index.php/Gamepad#Disable_Joystick_From_Controlling_Mouse

Tested on Ubuntu 14.04 LTS

**Comment by uglyDwarf** [comment]
Hopefully with the new revision this shouldn't be needed anymore...
Kind regards,
Michal

**Comment by mwozny123** [comment]
not needed since https://github.com/uglyDwarf/evdevshift/commit/a06941f25c2014afb14e9e2a186cbf8ff472fceb Apr 11, 2016 version
