### ISSUE TITLE
Can't compile - multiple 'undeclared here (not in a function)' errors

### ISSUE THREAD

**Issue by mwozny123** [uglyDwarf/evdevshift#2]
I've just noticed that new changes has been pushed to the git repo.

Unfortunately this 6 commit seems to have a compilation problem. 
Maybe not all changes were pushed to Git?

> evdevshift.c:509:12: error: ‘KEY_NUMERIC_A’ undeclared here (not in a function)
> (..)
> 
> evdevshift.c:510:12: error: ‘KEY_NUMERIC_B’ undeclared here (not in a function)
> (..)

Full log in attachment:
[compilation_error.txt](https://github.com/uglyDwarf/evdevshift/files/208178/compilation_error.txt)

**Comment by uglyDwarf** [comment]
Fixes the problem on my 14.04 machine by using already preprocessed name list.
Kind regards,

Michal
