### ISSUE TITLE
X-plane 10 problem. Saiteck Mode swicher has the same button mapping for A and B possition

### ISSUE THREAD

**Issue by mwozny123** [uglyDwarf/evdevshift#3]
I've evdevshift commit no 4 version (commit no 6 cant compile - already reported).

My joystick mode selector on screenshot:
![modeswitcher](https://cloud.githubusercontent.com/assets/650550/14349084/cb845146-fcc0-11e5-80ac-8cc3219790ec.jpeg)

X-plane 10 recognize the same button mappings for Mode A,B (different when OFF), but the same for A and B, so it's a partial sucess;). 

My configuration's in attachment:

[Saiteck_AV8R-01.conf](https://github.com/uglyDwarf/evdevshift/files/208225/Saiteck_AV8R-01.conf.txt)

Evdevshift console output seems to be ok:

> (...)
> State:
>       Button BUTTON_12D => 301
>         Button BTN_BASE5 (298) will be mapped to 0.
>         Button BTN_BASE4 (297) will be mapped to 1.
>         Button BTN_BASE3 (296) will be mapped to 2.
>         Button BTN_BASE2 (295) will be mapped to 3.
>         Button BTN_BASE (294) will be mapped to 4.
>         Button BTN_PINKIE (293) will be mapped to 5.
>         Button BTN_TOP2 (292) will be mapped to 6.
> State:
>       Button BUTTON_12C => 300
>         Button BTN_BASE5 (298) will be mapped to 7.
>         Button BTN_BASE4 (297) will be mapped to 8.
>         Button BTN_BASE3 (296) will be mapped to 9.
>         Button BTN_BASE2 (295) will be mapped to 10.
>         Button BTN_BASE (294) will be mapped to 11.
>         Button BTN_PINKIE (293) will be mapped to 12.
>         Button BTN_TOP2 (292) will be mapped to 13.
> Axis Maps:
> File 'dev.conf' opened.
> New device created.

But X-plane has a problem with it. E.g. 
mode OFF - button "T3" (a.k.a "BTN_BASE") - recognized by X-plane as button 327
mode A (a.k.a. "KEY_#300" [evdevtest-qt]) - button "T3" - recognized by X-plane as button 167
mode B (a.k.a. "KEY_#301" [evdevtest-qt])- button "T3" - recognized by X-plane as button 167

I've also tired to use such configuration:

> if(BUTTON_12C||BUTTON_12D){

but it didn't work for me:

> Parsing file 'dev.conf'.
> Unmatched character '|' at line 28.
> Unmatched character '|' at line 28.
> Config parser: syntax error, unexpected TOKEN_STRING, expecting TOKEN_RPAREN in file dev.conf, line 28 near 'BUTTON_12D'.

**Comment by uglyDwarf** [comment]
Hi,
please try the newly committed version - it should fix the problems you reported; I can't try on the Aviator, but my X52 has similar mode switch and with it the thing seems to be working as expected...
Let me know if it solves the problems you experience...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Works great now:) Many thanks:)
