### ISSUE TITLE
evdevshift don't work for Axis

### ISSUE THREAD

**Issue by mwozny123** [uglyDwarf/evdevshift#8]
Hi 

I'd like to add new virtual axis (when button 12C or 12D is down).
For buttons there's no problem but I can't make it work for none of axis.
Moreover in that configuration ([Saiteck_AV8R-01.conf.txt](https://github.com/uglyDwarf/evdevshift/files/405703/Saiteck_AV8R-01.conf.txt)) new Joystic is not visible in jstest-gtk.

Log:

> $ sudo setfacl -m user:$(whoami):rw /dev/uinput
> $ ./evdevshift --config presets/Saiteck_AV8R-01.conf
> Parsing file 'presets/Saiteck_AV8R-01.conf'.
> open: Permission denied
> open: Permission denied
> open: Permission denied
> open: Permission denied
> open: Permission denied
> open: Permission denied
> open: Permission denied
> open: Permission denied
> open: Permission denied
> Device: 'Saitek AV8R Joystick'.
> Names defined:
> Name def: Axis ABS_HAT0Y => 17
> Name def: Axis ABS_HAT0X => 16
> Name def: Axis ABS_THROTTLE => 6
> Name def: Axis ABS_RZ => 5
> Name def: Axis ABS_Z => 2
> Name def: Axis ABS_Y => 1
> Name def: Axis ABS_X => 0
> Name def: Button BUTTON_12D => 301
> Name def: Button BUTTON_12C => 300
> Name def: Button BTN_BASE6 => 299
> Name def: Button BTN_BASE5 => 298
> Name def: Button BTN_BASE4 => 297
> Name def: Button BTN_BASE3 => 296
> Name def: Button BTN_BASE2 => 295
> Name def: Button BTN_BASE => 294
> Name def: Button BTN_PINKIE => 293
> Name def: Button BTN_TOP2 => 292
> Name def: Button BTN_TOP => 291
> Name def: Button BTN_THUMB2 => 290
> Name def: Button BTN_THUMB => 289
> Name def: Button BTN_TRIGGER => 288
> State:
>       Button BUTTON_12D => 301
>         Axis ABS_Y (1) will be mapped to 300/301.
>         Axis ABS_X (0) will be mapped to 302/303.
>         Axis ABS_Z (2) will be mapped to 304/305.
>         Button BTN_BASE6 (299) will be mapped to 306.
>         Button BTN_BASE5 (298) will be mapped to 307.
>         Button BTN_BASE4 (297) will be mapped to 308.
>         Button BTN_BASE3 (296) will be mapped to 309.
>         Button BTN_BASE2 (295) will be mapped to 310.
>         Button BTN_BASE (294) will be mapped to 311.
>         Button BTN_PINKIE (293) will be mapped to 312.
>         Button BTN_TOP2 (292) will be mapped to 313.
> State:
>       Button BUTTON_12C => 300
>         Axis ABS_Y (1) will be mapped to 314/315.
>         Axis ABS_X (0) will be mapped to 316/317.
>         Axis ABS_Z (2) will be mapped to 318/319.
>         Button BTN_BASE6 (299) will be mapped to 320.
>         Button BTN_BASE5 (298) will be mapped to 321.
>         Button BTN_BASE4 (297) will be mapped to 322.
>         Button BTN_BASE3 (296) will be mapped to 323.
>         Button BTN_BASE2 (295) will be mapped to 324.
>         Button BTN_BASE (294) will be mapped to 325.
>         Button BTN_PINKIE (293) will be mapped to 326.
>         Button BTN_TOP2 (292) will be mapped to 327.
> Axis Maps:
> File 'presets/Saiteck_AV8R-01.conf' opened.
> New device created.

When there's one Axis in conf ([Saiteck_AV8R-01.conf-oneAxis.txt](https://github.com/uglyDwarf/evdevshift/files/405714/Saiteck_AV8R-01.conf-oneAxis.txt)) it still doesn't work but at least second joystic is visible in jstest-gtk

Could you help?

**Comment by uglyDwarf** [comment]
Will take a look at that...
Kind regards,
Michal

**Comment by uglyDwarf** [comment]
Hello,
I tried to reproduce the problem, but so far it seems to work for me...
That said, there are few things to look for: first of all, if the new device didn't show up in the jstest-gtk, then look using the evtest - chances are, that the device was not recognized as a joystick (maybe due to disappearing ABS_X?). Also the axis mapping is meant for Hats, so it translates its movement to button presses...
Let me know if it explains the behavior you see...
Kind regards,
Michal

**Comment by mwozny123** [comment]
I was looking for additional Axises but each axis was mapped to 2 buttons. 
If the axis if pushed more than half each way button press is simulated.

Can you add option to create additional axises, if axis or hat is used in own configuration e.g.:

```
if(BUTTON_12C){
  axis ABS_RZ
  axis ABS_HAT0Y
  axis ABS_HAT0X
}
```

?
so here if BUTTON_12C is keydown additional axis would be created for ABS_RZ and one "axis" for HAT.

IMHO it's more expected than mapping axis to buttons.

**Comment by uglyDwarf** [comment]
Hello,
this particular feature helps to make hats to behave more "naturally"; like "incremental" panning - when hat is mapped to buttons, then it is easy, while with axes it is impossible (at least in X-Plane AFAIK)...
I'll try to think about it...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Thanks for you work and for this feature:)

I've noticed there's a small issue with new axis assigning numbers.

New_axises numbers starts from 0 (instead of last axis number +1),
so steering real axis 0 is "overriden" by newly created axis 0.
It's hard to explain, hope the example will be clear:

Here's my setting for axises

```
if(BUTTON_12C){
  new_axis ABS_Z
}

if(BUTTON_12D){
  new_axis ABS_Z
}

```

Log:

```
State:
      Button BUTTON_12D => 301
        Axis ABS_Z (2) will be mapped to axis 0.
(..)
State:
      Button BUTTON_12C => 300
        Axis ABS_Z (2) will be mapped to axis 1.
(..)
```

This way I can control axis 0 using "real" axis 0 (ABS_X) or by the new_axis 0(ABS_Z when button (switcher) is 12C is "pressed").
On this example the same apply for axis 1(ABS_Y) when button 12D is "pressed", can be controlled by new axis 1 (ABS_Z + button 12D)

**Comment by uglyDwarf** [comment]
This is strange, my test shows the first unused axis is assigned to the new axis...
Could you please post the full log - so I can see what exactly is going on in there...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Log:

```
./evdevshift --config presets/Saiteck_AV8R-01_2.conf 
Parsing file 'presets/Saiteck_AV8R-01_2.conf'.
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
Device: 'Saitek AV8R Joystick'.
Names defined:
Name def: Axis ABS_HAT0Y => 17
Name def: Axis ABS_HAT0X => 16
Name def: Axis ABS_THROTTLE => 6
Name def: Axis ABS_RZ => 5
Name def: Axis ABS_Z => 2
Name def: Axis ABS_Y => 1
Name def: Axis ABS_X => 0
Name def: Button BUTTON_12D => 301
Name def: Button BUTTON_12C => 300
Name def: Button BTN_BASE6 => 299
Name def: Button BTN_BASE5 => 298
Name def: Button BTN_BASE4 => 297
Name def: Button BTN_BASE3 => 296
Name def: Button BTN_BASE2 => 295
Name def: Button BTN_BASE => 294
Name def: Button BTN_PINKIE => 293
Name def: Button BTN_TOP2 => 292
Name def: Button BTN_TOP => 291
Name def: Button BTN_THUMB2 => 290
Name def: Button BTN_THUMB => 289
Name def: Button BTN_TRIGGER => 288
State:
      Button BUTTON_12D => 301
        Axis ABS_Z (2) will be mapped to axis 0.
State:
      Button BUTTON_12C => 300
        Axis ABS_Z (2) will be mapped to axis 1.
Axis Maps:
File 'presets/Saiteck_AV8R-01_2.conf' opened.
New device created.
```

Config file:
[Saiteck_AV8R-01_2.conf.txt](https://github.com/uglyDwarf/evdevshift/files/441272/Saiteck_AV8R-01_2.conf.txt)

Thanks
Marcin

**Comment by uglyDwarf** [comment]
Hello,
can you try now?
Kind regards,
Michal

**Comment by mwozny123** [comment]
It's nearly done. 
In jstest-gtk works fine. New Axis 3 and 4 are added:

```
(..)
        Axis ABS_RZ (5) will be mapped to axis 3.
(..)
        Axis ABS_RZ (5) will be mapped to axis 4.

```

They are not the last one (I've 7 'real' axises) but the others one got higher numbers, so no conflicts:)

There's a problem in X-plane 10. New axis are working and visible, but they move also oryginal axis. 
I've "Yaw" mapped under this axis ABS_RZ and when mode switcher (a.k.a shift) is set to 'A' (or 'B') new axis is moved in X-plane, but unfortunately "Yaw" axis is also moved.

I've recorded a screen:
https://youtu.be/_bEVGfL8cEM
- up to 12 sec modeswitcher set to "Off", moving "Yaw" (and duplicated axis, probably from oryginal joystick device, not virtual(evdevshift))
- from 12 sec modeswicher changed to "A" moving "new_Axis" (and unfortunately X-plane "Yaw" in the same time)
- from 20 sec modeswitcher changed to "B" moving "new_Axis" (and unfortunately X-plane "Yaw" in the same time)

Maybe it related with visiblity/duplicated axises from:
https://github.com/uglyDwarf/evdevshift/issues/5 ("in X-plane 10 axises are duplicated (..) ") 
?

Could you fix that? 
BR
Marcin

**Comment by uglyDwarf** [comment]
Hello,
if I understand it correctly, the unwanted moving axis the X-Plane sees is on the source device (the physical one), not on the newly created device (there it should move only when both mode switching buttons are off) - am I correct?
If so, the only thing you can do is to assign the yaw to the axis on the new device, and unmap the "real" one... Or you can set the config to grab the device, so the X-Plane won't see movement of any of its axes (but will see the axes)... Third option might be setting the event device permissions/ACL so you can't read/write it - then the X-Plane won't use it at all...

Kind regards,

Michal

**Comment by mwozny123** [comment]
Well, it hard to tell is it "real" Axis or new one. Do you have idea how to check it?

Newly created axises got numbers (in jstest) 3 and 4 and old ("real") is no. 5 (hope that's helpful).
Don't know how's that mapped by X-plane.

About you options:
1. What happen when you unmap "real" one will I be still able to use that axis or only newly created?
2. I can try it - how to "set the config to grab the device"?
3. Maybe this one would be the best solution. Will it also solve https://github.com/uglyDwarf/evdevshift/issues/5, so this way we would have solved 2 problems:) ?

**Comment by uglyDwarf** [comment]
Hello,
X-Plane puts axes from a device together, so I'd say that the first axis you see moving is the real one, while the block with the "switched axes" is the new device...

ad 1) you just go to the dropbox selecting what the axis does and there should be something like "nothing" or so; just indicate that it shouldn't use the axis at all...

ad 2) in the config, there is the device line - just prefix the device "xxx" with word grab ('grab device "xxx"')...

ad 3) It would, but I'm still thinking about how to make it easiest - you need the old device to be accessible by evdevshift, not accessible by X-Plane and the new device must be accessible by X-Plane... Maybe if you remove the ACL from the "real" device after you started the evdevshift, that might work...

Kind regards,
Michal

Kind regards,
Michal

**Comment by mwozny123** [comment]
ad 1) :/

ad 3) ACLs seems above my Linux knowledge. I was thinking about maybe adding a evdev group and adding read access and removing rwx for other. Googling around ACLs looks for somethink similiar/better.

ad 2) I replaced line 
`device "Saitek AV8R Joystick"`
with:
`grab device "Saitek AV8R Joystick"`
not sure what it does but - It worked:) Good job :+1: 
First 5 axises in X-plane are inactive now, then I have 9 new axises:)

What does the "grab" option? Maybe it worth to add it to automatic created configurations?;)

**Comment by mwozny123** [comment]
ps: isn't Evdevshit enough mature to announce it e.g. on X-plane(and/or Linux) forum as new thread?:) 
More people would be able to find it. 
For me it a great/must have joystick app. 
It made my joystick much better.
Once again thanks for you work and time:)

**Comment by uglyDwarf** [comment]
Hello,
ad 2) The grab word indicates that the application requests exclusive access to the device, so other applications can't read from it... I'm not putting it there on purpose - it doesn't seem nice ;) The X-Plane does enumerate the axes, but it can't read them...

ad 3) I'm using this:
sudo setfacl -m u:username:rw
This adds read/write access to the user 'username'... getfacl will tell you what ACLs are in place. Also ls indicates there are ACLs by + sign aside from rights when using something like 'ls -lsaF'...

I'm working on one more thing that I'd like to finish before going full public; I just made a python script that is able to test evdevshift's working - it will enable quick regression testing and code coverage on the full evdevshift (instead of just the main part, which was why I didn't see the axis mapping problem). I have the main part ready, so I expect to have it ready during this weekend...

Kind  regards,

Michal

**Comment by mwozny123** [comment]
Change done. Now it's working. Closing
